CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY, 
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS addresses (
    address_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    address_line_one VARCHAR(255),
    address_line_two VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip_code VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS contacts (
    contact_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    email VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT contacts_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS plus_one (
    plus_one_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS attendance (
    attendance_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    attending BOOLEAN NOT NULL
);
