CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY, 
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS addresses (
    address_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    address_line_one VARCHAR(255),
    address_line_two VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip_code VARCHAR(10),
    CONSTRAINT addresses_fk_user_id_unique UNIQUE (fk_user_id)
);

CREATE TABLE IF NOT EXISTS contacts (
    contact_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    email VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT contacts_email_unique UNIQUE (email),
    CONSTRAINT contacts_fk_user_id_unique UNIQUE (fk_user_id)
);

CREATE TABLE IF NOT EXISTS party (
    party_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    attending BOOLEAN NOT NULL,
    note TEXT,
    CONSTRAINT party_fk_user_id_unique UNIQUE (fk_user_id)
);

CREATE TABLE IF NOT EXISTS party_pop (
    party_pop_id UUID PRIMARY KEY,
    fk_party_id INTEGER NOT NULL REFERENCES party(party_id) ON DELETE CASCADE,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL,
    age INTEGER NOT NULL CHECK (age > 0),
    phone_number VARCHAR(25),
    allergies TEXT,
    CONSTRAINT pary_pop_party_pop_id_unique UNIQUE (party_pop_id)
);
