CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    notes TEXT
);

CREATE TABLE addresses (
    address_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID REFERENCES users(user_id),
    address_line_one VARCHAR(255),
    address_line_two VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255), 
    zip_code INTEGER
);

CREATE TABLE contacts (
    contact_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID REFERENCES users(user_id),
    email VARCHAR(255),
    phone_number VARCHAR(255)
);

CREATE TABLE plus_one (
    plus_one_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id UUID REFERENCES users(user_id),
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);
